import os
from typing import List

from ..glyph_info import GlyphInfo


class CssStylesheetWriter:
    """Writes the @font-face stylesheet exposing one class per glyph with font variant support."""

    @staticmethod
    def _normalize_weight_and_style(
        variant_weight: str
    ) -> tuple[str, str]:
        """Maps variant names (e.g. 'BoldItalic', 'Light') to standard CSS font-weight and font-style values."""
        lower = variant_weight.lower()
        font_style = "italic" if "italic" in lower else "normal"

        if "thin" in lower:
            css_weight = "100"
        elif "extralight" in lower:
            css_weight = "200"
        elif "light" in lower:
            css_weight = "300"
        elif "bold" in lower:
            css_weight = "bold"
        elif "extrabold" in lower:
            css_weight = "800"
        elif "black" in lower:
            css_weight = "900"
        else:
            css_weight = "normal"

        return css_weight, font_style


    @classmethod
    def write(
            cls,
            output_dir: str,
            font_name: str,
            font_weight: str,
            glyphs_info: List[GlyphInfo]
    ) -> str:
        font_family_lower = font_name.lower()
        variant_lower = font_weight.lower()

        # File binary names generated by FontBuilder: e.g. GameIcons-Bold.woff2
        font_file_basename = f"{font_name}-{font_weight}"

        # Convert variant to CSS-compliant font-weight and font-style attributes
        css_weight_val, css_style_val = cls._normalize_weight_and_style(font_weight)

        css_content = f"""/* {font_name} ({font_weight}) Font CSS */
@font-face {{
    font-family: '{font_name}';
    src: url('{font_file_basename}.woff2') format('woff2'),
         url('{font_file_basename}.woff') format('woff'),
         url('{font_file_basename}.ttf') format('truetype');
    font-weight: {css_weight_val};
    font-style: {css_style_val};
}}

.{font_family_lower}.{variant_lower} {{
    font-family: '{font_name}';
    font-weight: {css_weight_val};
    font-style: {css_style_val};
    font-size: 24px;
    line-height: 1;
    display: inline-block;
    direction: ltr;
    -webkit-font-smoothing: antialiased;
}}
"""
        # Append glyph pseudo-elements
        for info in glyphs_info:
            css_class = info.name.replace('_', '-').lower()
            css_content += f".{font_family_lower}-{variant_lower}-{css_class}::before {{ content: '\\{info.unicode_value:04X}'; }}\n"

        css_filename = f"{font_family_lower}-{variant_lower}.css"
        css_path = os.path.join(output_dir, css_filename)

        with open(css_path, 'w', encoding='utf-8') as f:
            f.write(css_content)

        return css_path
